name: New Relic Node.js Example
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Install New Relic agent
      run: npm install newrelic
    - name: Generate New Relic configuration file
      run: |
        echo "exports.config = {" >> newrelic.js
        echo "  app_name: ['auto-agent']," >> newrelic.js
        echo "  license_key: '${{ secrets.NEW_RELIC_LICENSE_KEY }}'," >> newrelic.js
        echo "  logging: {" >> newrelic.js
        echo "    level: 'info'" >> newrelic.js
        echo "  }" >> newrelic.js
        echo "};" >> newrelic.js
    - name: Copy New Relic configuration file
      run: cp newrelic.js ./newrelic.js
    - name: Start Node.js app
      run: npm start
